final url = 'http://192.168.91.85:3010/';
final registerationUrl = url + "register";
final loginUrl = url + "login";
final coursesurl = url + "courses";
final notsUrl = url + "notifications";
final assignmentsUrl = url + "assignments";
final resultsUrl = url + "results";
final feesUrl = url + "fees";
final registerCourses = url + "registercourse";
